# coding: utf-8

"""
    DLRN API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import dlrnapi_client
from dlrnapi_client.rest import ApiException
from dlrnapi_client.models.params_3 import Params3


class TestParams3(unittest.TestCase):
    """ Params3 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParams3(self):
        """
        Test Params3
        """
        model = dlrnapi_client.models.params_3.Params3()


if __name__ == '__main__':
    unittest.main()
