# coding: utf-8

"""
    DLRN API

    DLRN API client

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from dlrnapi_client.models.agg_query import AggQuery


class TestAggQuery(unittest.TestCase):
    """AggQuery unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAggQuery(self):
        """Test AggQuery """
        model = AggQuery()
        expected = {'aggregate_hash': None, 'success': None}
        self.assertEqual(model.to_dict(), expected)


if __name__ == '__main__':
    unittest.main()
