# coding: utf-8

"""
    DLRN API

    DLRN API client

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from dlrnapi_client.models.ci_vote import CIVote


class TestCIVote(unittest.TestCase):
    """CIVote unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCIVote(self):
        """Test CIVote """
        model = CIVote()
        expected = {'job_id': None, 'success': None, 'url': None,
                    'timestamp': None, 'notes': None, 'distro_hash': None,
                    'commit_hash': None, 'in_progress': None,
                    'component': None, 'aggregate_hash': None}
        self.assertEqual(model.to_dict(), expected)


if __name__ == '__main__':
    unittest.main()
