# coding: utf-8

"""
    DLRN API

    DLRN API client

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from dlrnapi_client.models.params_2 import Params2


class TestParams2(unittest.TestCase):
    """Params2 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParams2(self):
        """Test Params2 """
        model = Params2()
        expected = {'commit_hash': None, 'success': None, 'distro_hash': None}
        self.assertEqual(model.to_dict(), expected)


if __name__ == '__main__':
    unittest.main()
