# coding: utf-8

"""
    DLRN API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import dlrnapi_client
from dlrnapi_client.rest import ApiException
from dlrnapi_client.models.params_5 import Params5


class TestParams5(unittest.TestCase):
    """ Params5 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParams5(self):
        """
        Test Params5
        """
        model = dlrnapi_client.models.params_5.Params5()


if __name__ == '__main__':
    unittest.main()
