# coding: utf-8

"""
    DLRN API

    DLRN API client

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from dlrnapi_client.models.ci_agg_vote import CIAggVote


class TestCIAggVote(unittest.TestCase):
    """CIAggVote unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCIAggVote(self):
        """Test CIAggVote """
        model = CIAggVote()
        expected = {'job_id': None, 'success': None, 'url': None,
                    'timestamp': None, 'notes': None, 'in_progress': None,
                    'aggregate_hash': None}
        self.assertEqual(model.to_dict(), expected)


if __name__ == '__main__':
    unittest.main()
