# coding: utf-8

"""
    DLRN API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import dlrnapi_client
from dlrnapi_client.rest import ApiException
from dlrnapi_client.models.inline_response_201 import InlineResponse201


class TestInlineResponse201(unittest.TestCase):
    """ InlineResponse201 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse201(self):
        """
        Test InlineResponse201
        """
        model = dlrnapi_client.models.inline_response_201.InlineResponse201()


if __name__ == '__main__':
    unittest.main()
