# coding: utf-8

"""
    DLRN API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import dlrnapi_client
from dlrnapi_client.rest import ApiException
from dlrnapi_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = dlrnapi_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_api_last_tested_repo_get(self):
        """
        Test case for api_last_tested_repo_get

        
        """
        pass

    def test_api_last_tested_repo_post(self):
        """
        Test case for api_last_tested_repo_post

        
        """
        pass

    def test_api_promote_post(self):
        """
        Test case for api_promote_post

        
        """
        pass

    def test_api_remote_import_post(self):
        """
        Test case for api_remote_import_post

        
        """
        pass

    def test_api_repo_status_get(self):
        """
        Test case for api_repo_status_get

        
        """
        pass

    def test_api_report_result_post(self):
        """
        Test case for api_report_result_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
