---
- job:
    name: tox-py27-centos-7
    pre-run: playbooks/py27-install.yaml
    run: playbooks/tox_run.yaml

- job:
    name: tox-pre
    parent: tox
    pre-run: playbooks/preparation.yaml
    run: playbooks/tox_run.yaml

- job:
    name: tox-py310-fedora
    parent: tox-pre
    pre-run: playbooks/py310-install.yaml
    vars:
      tox_envlist: py310
      python_version: 3.10

- job:
    name: tox-py39-centos-9
    parent: tox-pre
    vars:
      tox_envlist: py39
    nodeset:
      nodes:
        - label: cloud-centos-9-stream
          name: cloud-centos-9-stream

- job:
    name: tox-py36-centos-8
    parent: tox-pre
    vars:
      tox_envlist: py36
    nodeset: centos-latest-pod

- project:
    name: dlrnapi_client
    check:
      jobs: &jobs
        - tox-pep8:
            nodeset: fedora-latest-pod
        - tox-py27-centos-7:
            nodeset: centos-7-pod
            vars:
                tox_extra_args: -vv --skip-missing-interpreters=true
                tox_install_siblings: false
        - tox-py36-centos-8
        - tox-py39-centos-9
        - tox-py310-fedora:
            nodeset: fedora-latest-pod
        - dlrn-api-functional-centos-7
        - dlrn-api-functional-centos-8
    gate:
      jobs: *jobs
    release:
      jobs:
        - upload-pypi
