---
- job:
    name: tox-py27-centos-7
    pre-run: playbooks/py27-install.yaml
    run: playbooks/tox_run.yaml

- job:
    name: tox-pre
    parent: tox
    pre-run: playbooks/preparation.yaml
    run: playbooks/tox_run.yaml

- job:
    name: tox-py312-fedora
    parent: tox-pre
    pre-run: playbooks/py312-install.yaml
    vars:
      tox_envlist: py312
      python_version: 3.10

- job:
    name: tox-py39-centos-9
    parent: tox-pre
    vars:
      tox_envlist: py39
    nodeset:
      nodes:
        - label: cloud-centos-9-stream
          name: cloud-centos-9-stream

- project:
    name: dlrnapi_client
    check:
      jobs: &jobs
        - tox-pep8:
            nodeset: fedora-latest-pod
        - tox-py27-centos-7:
            nodeset:
              nodes:
                - name: centos-7
                  label: rdo-centos-7
            vars:
                tox_extra_args: -vv --skip-missing-interpreters=true
                tox_install_siblings: false
        - tox-py39-centos-9
        - tox-py312-fedora:
            nodeset:
              nodes:
                - name: zuul-worker-f40
                  label: zuul-worker-f40
        - dlrn-api-functional-centos-9
    gate:
      jobs: *jobs
    release:
      jobs:
        - upload-pypi
