# coding: utf-8

"""
    DLRN API

    DLRN API client

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems


class Params4(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, commit_hash=None, distro_hash=None, promote_name=None):
        """Params4 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'commit_hash': 'str',
            'distro_hash': 'str',
            'promote_name': 'str'
        }

        self.attribute_map = {
            'commit_hash': 'commit_hash',
            'distro_hash': 'distro_hash',
            'promote_name': 'promote_name'
        }

        self._commit_hash = commit_hash
        self._distro_hash = distro_hash
        self._promote_name = promote_name

    @property
    def commit_hash(self):
        """Gets the commit_hash of this Params4.

        commit_hash of the repo to be promoted.

        :return: The commit_hash of this Params4.
        :rtype: str
        """
        return self._commit_hash

    @commit_hash.setter
    def commit_hash(self, commit_hash):
        """Sets the commit_hash of this Params4.

        commit_hash of the repo to be promoted.

        :param commit_hash: The commit_hash of this Params4.
        :type: str
        """
        if commit_hash is None:
            raise ValueError("Invalid value for `commit_hash`, must not be"
                             " `None`")

        self._commit_hash = commit_hash

    @property
    def distro_hash(self):
        """Gets the distro_hash of this Params4.

        distro_hash of the repo to be promoted.

        :return: The distro_hash of this Params4.
        :rtype: str
        """
        return self._distro_hash

    @distro_hash.setter
    def distro_hash(self, distro_hash):
        """Sets the distro_hash of this Params4.

        distro_hash of the repo to be promoted.

        :param distro_hash: The distro_hash of this Params4.
        :type: str
        """
        if distro_hash is None:
            raise ValueError("Invalid value for `distro_hash`, must not be "
                             "`None`")

        self._distro_hash = distro_hash

    @property
    def promote_name(self):
        """Gets the promote_name of this Params4.

        Name to be used for the promotion. In the current implementation,
        this is the name of the symlink to be created

        :return: The promote_name of this Params4.
        :rtype: str
        """
        return self._promote_name

    @promote_name.setter
    def promote_name(self, promote_name):
        """Sets the promote_name of this Params4.

        Name to be used for the promotion. In the current implementation,
        this is the name of the symlink to be created

        :param promote_name: The promote_name of this Params4.
        :type: str
        """
        if promote_name is None:
            raise ValueError("Invalid value for `promote_name`, must not be "
                             "`None`")

        self._promote_name = promote_name

    def to_dict(self):
        """Returns the model properties as a dict """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model """
        return pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint` """
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal """
        if not isinstance(other, Params4):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal """
        return not self == other
